# Generated by Django 5.1.1 on 2024-09-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('credited_on_date', models.DateField(blank=True, null=True)),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('irctc_order_no', models.BigIntegerField(blank=True, null=True)),
                ('bank_booking_ref_no', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('txn_date', 'credited_on_date', 'irctc_order_no', 'bank_booking_ref_no'), name='unique_bookingdata_constraint')],
            },
        ),
        migrations.CreateModel(
            name='RefundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('debited_on_date', models.DateField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('irctc_order_no', models.BigIntegerField(blank=True, null=True)),
                ('bank_booking_ref_no', models.BigIntegerField(blank=True, null=True)),
                ('bank_refund_ref_no', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('refund_date', 'debited_on_date', 'irctc_order_no', 'bank_booking_ref_no', 'bank_refund_ref_no'), name='unique_refunddata_constraint')],
            },
        ),
    ]
